find:
  fields:
    query:
      required: true
      example: skjøteledning
      selector:
        text:
    config_entry_id:
      selector:
        config_entry:
          integration: tingsted
search:
  fields:
    query:
      required: true
      example: hammer
      selector:
        text:
    config_entry_id:
      selector:
        config_entry:
          integration: tingsted
add_items:
  fields:
    box:
      required: true
      example: B3
      selector:
        text:
    items:
      required: true
      example: "hammer x2"
      selector:
        text:
          multiple: true
    config_entry_id:
      selector:
        config_entry:
          integration: tingsted
lend:
  fields:
    item_id:
      required: true
      selector:
        number:
          min: 1
          max: 100000000
          mode: box
    to:
      required: true
      example: Ola
      selector:
        text:
    due:
      selector:
        date:
    config_entry_id:
      selector:
        config_entry:
          integration: tingsted
return_item:
  fields:
    item_id:
      required: true
      selector:
        number:
          min: 1
          max: 100000000
          mode: box
    config_entry_id:
      selector:
        config_entry:
          integration: tingsted
